name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: lscpu
      run: lscpu

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 9.0.x

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release

    - name: Benchmark Popcnt
      run:  dotnet run -p Equativ.RoaringBitmaps.Benchmarks -c Release -- -f '*Popcnt*'

    - name: Benchmark against CRoaring
      run:  dotnet run -p Equativ.RoaringBitmaps.Benchmarks -c Release -- -f '*CRoaring*'